# JULY 맛 기준 총 주문량
WITH JULY_FLAVOR AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
        FROM JULY
        GROUP BY FLAVOR
),
# 상반기 맛 기준 총 주문량
FIRST_HALF_FLAVOR AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS FIRST_HALF_SUM
        FROM FIRST_HALF
        GROUP BY FLAVOR
)
# JOIN하여 총 주문량 기준 상위 3개만 출력
SELECT JF.FLAVOR
    FROM JULY_FLAVOR JF JOIN FIRST_HALF_FLAVOR FHF ON JF.FLAVOR=FHF.FLAVOR
    ORDER BY (JF.JULY_SUM + FHF.FIRST_HALF_SUM) DESC
    LIMIT 3
