SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
    FROM ITEM_INFO II JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID # ID로 조인
    WHERE IT.PARENT_ITEM_ID IN ( # RARE 등급인 ID들을 PARENT로 가지는
        SELECT ITEM_ID
            FROM ITEM_INFO
            WHERE RARITY = 'RARE'
    )
    ORDER BY II.ITEM_ID DESC # ID들 내림차순
